## 판다스 기초

### 판다스 패키지 로드

```python
import pandas as pd
```

In [4]:
import pandas as pd

In [12]:
# DataFrame을 직접 생성할때 사용. 
# 파이썬 딕셔너리 사용
raw_data = {
    'name' : ['홍길동', '김철수', '이영희', '박민수', '성유고', '애슐리'],
    'age' : [20, 21, 22, 23, 30, 29],
    'major' : ['데이터분석', '웹개발', '인공지능', '임베디드', '인공지능', '웹개발'],
    'score' : [85, 90, 95, 80, 90, 100]
}

raw_data

{'name': ['홍길동', '김철수', '이영희', '박민수', '성유고', '애슐리'],
 'age': [20, 21, 22, 23, 30, 29],
 'major': ['데이터분석', '웹개발', '인공지능', '임베디드', '인공지능', '웹개발'],
 'score': [85, 90, 95, 80, 90, 100]}

In [18]:
df = pd.DataFrame(raw_data)

df

  name  age  major  score
0  홍길동   20  데이터분석     85
1  김철수   21    웹개발     90
2  이영희   22   인공지능     95
3  박민수   23   임베디드     80
4  성유고   30   인공지능     90
5  애슐리   29    웹개발    100

#### 기본 통계

In [15]:
# 숫자타입 필드만 통계 가능

df.describe()

             age       score
count   6.000000    6.000000
mean   24.166667   90.000000
std     4.262237    7.071068
min    20.000000   80.000000
25%    21.250000   86.250000
50%    22.500000   90.000000
75%    27.500000   93.750000
max    30.000000  100.000000

#### 컬럼(열) 선택

In [20]:
# DataFrame에서 필요한 컬럼만 확인 또는 할당(복사)

df['name']

0    홍길동
1    김철수
2    이영희
3    박민수
4    성유고
5    애슐리
Name: name, dtype: str

In [23]:
# 컬럼 선택의 편의성을 위해 추가된 방식. 위와 동일

df.name

0    홍길동
1    김철수
2    이영희
3    박민수
4    성유고
5    애슐리
Name: name, dtype: str

- DataFrame에서 하나의 컬럼만 가져오면 `Series` 타입

In [24]:
# 대괄호가 하나인지 두개인지로 시리즈와 데이터프레임 구분

df[['name', 'age']]

  name  age
0  홍길동   20
1  김철수   21
2  이영희   22
3  박민수   23
4  성유고   30
5  애슐리   29

#### 로우(행) 선택

In [26]:
# 인덱스 이름을 기준

df.loc[0]

name       홍길동
age         20
major    데이터분석
score       85
Name: 0, dtype: object

In [29]:
# 위치번호 기준. 인덱스를 다른 값으로 바꿨을 때 사용하는 방법

df.iloc[0]

name       홍길동
age         20
major    데이터분석
score       85
Name: 0, dtype: object

In [34]:
# 시리즈의 인덱스로 각 열의 값을 확인

df.loc[0]['major']

'데이터분석'

In [36]:
# 슬라이싱으로 여러행 선택
# 파이썬 슬라이싱 규칙(뒤의 수 n-1까지 조회)에서 벗어남. 뒤의 수 그대로 조회

df.loc[0:2]

  name  age  major  score
0  홍길동   20  데이터분석     85
1  김철수   21    웹개발     90
2  이영희   22   인공지능     95

In [37]:
df.iloc[0:2]

  name  age  major  score
0  홍길동   20  데이터분석     85
1  김철수   21    웹개발     90

#### 행선택, 인덱스행(loc)과 위치행값(iloc) 차이

In [49]:
df2 = pd.DataFrame(raw_data,
                   index=['S0001', 'S0003', 'S0005', 'S0007', 'S0009', 'S0011'])

df2

      name  age  major  score
S0001  홍길동   20  데이터분석     85
S0003  김철수   21    웹개발     90
S0005  이영희   22   인공지능     95
S0007  박민수   23   임베디드     80
S0009  성유고   30   인공지능     90
S0011  애슐리   29    웹개발    100

In [53]:
df2.loc['S0001':'S0006']

      name  age  major  score
S0001  홍길동   20  데이터분석     85
S0003  김철수   21    웹개발     90
S0005  이영희   22   인공지능     95

In [46]:
df2.iloc[1:4]

      name  age major  score
s0003  김철수   21   웹개발     90
s0005  이영희   22  인공지능     95
s0007  박민수   23  임베디드     80

- loc는 부여받은 인덱스로 행선택, 슬라이싱
- iloc는 원래부터의 위치값(파이썬 배열의 인덱스)와 동일

#### 행과 열 함께 선택

In [56]:
df.loc[0, 'name']

'홍길동'

In [61]:
# 인덱스를 따로 부여하지 않은 DF에서 행과 열 선택

df.loc[0:2, ['name', 'age']]

  name  age
0  홍길동   20
1  김철수   21
2  이영희   22

In [62]:
# 인덱스를 따로 부여한 DF에서 행과 열 선택

df2.loc['S0001':'S0004', ['name', 'age']]

      name  age
S0001  홍길동   20
S0003  김철수   21

In [64]:
df3 = df2.loc['S0001':'S0004', ['name', 'age']]

df3 # 새 DataFrame 생성

      name  age
S0001  홍길동   20
S0003  김철수   21

#### 조건조회

- SQL WHERE 절과 동일

In [65]:
df['score'] >= 90

0    False
1     True
2     True
3    False
4     True
5     True
Name: score, dtype: bool

In [66]:
df[df['score'] >= 90]

  name  age major  score
1  김철수   21   웹개발     90
2  이영희   22  인공지능     95
4  성유고   30  인공지능     90
5  애슐리   29   웹개발    100

- NumPy와 동일한 조건 연산
- 파이썬 : and, or, not 사용
- NumPy, Pandas : &, |, ~ 사용

In [69]:
# 점수가 90점 초과이고 나이가 21살 이상인 학생 데이터 참/거짓 여부

(df['score'] > 90) & (df['age'] >= 21)

0    False
1    False
2     True
3    False
4    False
5     True
dtype: bool

In [71]:
df[(df['score'] > 90) & (df['age'] >= 21)]

  name  age major  score
2  이영희   22  인공지능     95
5  애슐리   29   웹개발    100

In [75]:
# 점수가 90점 초과이거나 나이가 21살 이상 둘 중 하나라도 참인 데이터 조회

df[(df['score'] > 90) | (df['age'] >= 21)]

  name  age major  score
1  김철수   21   웹개발     90
2  이영희   22  인공지능     95
3  박민수   23  임베디드     80
4  성유고   30  인공지능     90
5  애슐리   29   웹개발    100

#### 컬럼 추가

- 사용하던 DF 이외에 필요한 컬럼이 생길 때 추가

In [76]:
df

  name  age  major  score
0  홍길동   20  데이터분석     85
1  김철수   21    웹개발     90
2  이영희   22   인공지능     95
3  박민수   23   임베디드     80
4  성유고   30   인공지능     90
5  애슐리   29    웹개발    100

In [81]:
# 80점을 초과하는 학생만 통과
# 같은 이름의 컬럼은 새로 추가 안됨

df['pass'] = df['score'] > 80

df

  name  age  major  score   pass
0  홍길동   20  데이터분석     85   True
1  김철수   21    웹개발     90   True
2  이영희   22   인공지능     95   True
3  박민수   23   임베디드     80  False
4  성유고   30   인공지능     90   True
5  애슐리   29    웹개발    100   True

In [89]:
df['score_bonus'] = df['score'] + 5

df

  name  age  major  score   pass  score_bonus
0  홍길동   20  데이터분석     85   True           90
1  김철수   21    웹개발     90   True           95
2  이영희   22   인공지능     95   True          100
3  박민수   23   임베디드     80  False           85
4  성유고   30   인공지능     90   True           95
5  애슐리   29    웹개발    100   True          105

#### 컬럼 수정

- 기존 컬럼 수정

In [90]:
df['score_bonus'] = df['score_bonus'] - 2

df

  name  age  major  score   pass  score_bonus
0  홍길동   20  데이터분석     85   True           88
1  김철수   21    웹개발     90   True           93
2  이영희   22   인공지능     95   True           98
3  박민수   23   임베디드     80  False           83
4  성유고   30   인공지능     90   True           93
5  애슐리   29    웹개발    100   True          103

In [94]:
# 행 선택에서 score_bonus 점수가 100점 초과하는 행만 선택 후 score_bonus 값을 100으로 수정

df.loc[df['score_bonus'] > 100, 'score_bonus'] = 100

df

  name  age  major  score   pass  score_bonus
0  홍길동   20  데이터분석     85   True           88
1  김철수   21    웹개발     90   True           93
2  이영희   22   인공지능     95   True           98
3  박민수   23   임베디드     80  False           83
4  성유고   30   인공지능     90   True           93
5  애슐리   29    웹개발    100   True          100

#### 컬럼 삭제

- 불필요한 컬럼 삭제

In [96]:
df.drop(columns=['score_bonus'])

  name  age  major  score   pass
0  홍길동   20  데이터분석     85   True
1  김철수   21    웹개발     90   True
2  이영희   22   인공지능     95   True
3  박민수   23   임베디드     80  False
4  성유고   30   인공지능     90   True
5  애슐리   29    웹개발    100   True

In [97]:
df

  name  age  major  score   pass  score_bonus
0  홍길동   20  데이터분석     85   True           88
1  김철수   21    웹개발     90   True           93
2  이영희   22   인공지능     95   True           98
3  박민수   23   임베디드     80  False           83
4  성유고   30   인공지능     90   True           93
5  애슐리   29    웹개발    100   True          100

In [ ]:
# 두번 실행하면 에러(이미 삭제되었기 때문)

df.drop(columns=['score_bonus'], inplace=True)

In [99]:
df

  name  age  major  score   pass
0  홍길동   20  데이터분석     85   True
1  김철수   21    웹개발     90   True
2  이영희   22   인공지능     95   True
3  박민수   23   임베디드     80  False
4  성유고   30   인공지능     90   True
5  애슐리   29    웹개발    100   True

#### 행 추가

- 새로운 행 추가 방법

In [ ]:
df.loc[6] = ['최지우', 20, '웹개발', 88, True]

In [101]:
df

  name  age  major  score   pass
0  홍길동   20  데이터분석     85   True
1  김철수   21    웹개발     90   True
2  이영희   22   인공지능     95   True
3  박민수   23   임베디드     80  False
4  성유고   30   인공지능     90   True
5  애슐리   29    웹개발    100   True
6  최지우   20    웹개발     88   True

In [102]:
df.loc[7] = ['박선호', 25, '인공지능', 91, None]

In [104]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    8 non-null      str
 1   age     8 non-null      int64
 2   major   8 non-null      str
 3   score   8 non-null      int64
 4   pass    7 non-null      object
dtypes: int64(2), object(1), str(2)
memory usage: 452.0+ bytes

#### 데이터 읽기 쓰기

- 일반적으로 CSV 가장 많이 사용. excel, txt 등
- DB도 연동가능

In [105]:
df_bookstores = pd.read_csv('../data/부산지역서점.csv')

df_bookstores

,연번,시설명,전화번호,시군구,위도,경도,정렬번호
0,0,동사서독,0507-1396-1606,부산 금정구 금정로 87 2층,35.232421,129.086648,67
1,1,흰돌서점,051-625-9633,부산 수영구 남천서로32번길 38 흰돌서점,35.145707,129.106685,1
2,2,효원도서,051-517-6871,부산 금정구 부산대학로 63 (장전동),35.231481,129.084427,2
3,3,화명서점,051-337-0140,부산 북구 화명신도시로 130 로얄팰리스 110호 화명서점,35.235544,129.011331,3
4,4,현대서점,051-581-7963,부산 금정구 남산로 30 현대서점 (남산동),35.267302,129.088872,4
...,...,...,...,...,...,...,...
62,62,책과아이들,051-506-1448,부산 연제구 교대로16번길 20,35.196453,129.078185,62
63,63,책마을,051-753-8685,부산 연제구 안연로8번길 19 3층,35.188471,129.102055,63
64,64,카프카의 밤,051-665-5516,부산 연제구 고분로191번길 20,35.186167,129.104129,64
65,65,동네책방 아인,051-665-5516,부산 연제구 월드컵대로 221 다우빌딩 2층,35.188866,129.072650,65
66,66,책방 감,051-581-3318,부산 연제구 교대로24번길 10,35.195938,129.077150,66

In [106]:
# 데이터 쓰기

df.to_csv('../data/학생정보.csv', encoding='utf-8')

#### Execl

In [108]:
df_bookstores2 = pd.read_excel('../data/부산지역서점.xlsx')

df_bookstores2

,연번,시설명,전화번호,시군구,위도,경도,정렬번호
0,0,동사서독,0507-1396-1606,부산 금정구 금정로 87 2층,35.232421,129.086648,67
1,1,흰돌서점,051-625-9633,부산 수영구 남천서로32번길 38 흰돌서점,35.145707,129.106685,1
2,2,효원도서,051-517-6871,부산 금정구 부산대학로 63 (장전동),35.231481,129.084427,2
3,3,화명서점,051-337-0140,부산 북구 화명신도시로 130 로얄팰리스 110호 화명서점,35.235544,129.011331,3
4,4,현대서점,051-581-7963,부산 금정구 남산로 30 현대서점 (남산동),35.267302,129.088872,4
...,...,...,...,...,...,...,...
62,62,책과아이들,051-506-1448,부산 연제구 교대로16번길 20,35.196453,129.078185,62
63,63,책마을,051-753-8685,부산 연제구 안연로8번길 19 3층,35.188471,129.102055,63
64,64,카프카의 밤,051-665-5516,부산 연제구 고분로191번길 20,35.186167,129.104129,64
65,65,동네책방 아인,051-665-5516,부산 연제구 월드컵대로 221 다우빌딩 2층,35.188866,129.072650,65
66,66,책방 감,051-581-3318,부산 연제구 교대로24번길 10,35.195938,129.077150,66

#### PostgreSQL

- psycopg

In [109]:
import psycopg

In [116]:
conn = psycopg.connect(
    host='localhost',
    port=5432,
    dbname='ai_db',
    user='postgres',
    password='123456'
)

In [117]:
sql = 'select * from students'

df_postgres_students = pd.read_sql(sql, conn)

df_postgres_students

C:\Users\User\AppData\Local\Temp\ipykernel_20232\3672862669.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_postgres_students = pd.read_sql(sql, conn)

   id name             email  age  major                 created_at
0   1  김철수   kim@example.com   21   인공지능 2026-09-17 15:52:28.826805
1   2  이영희   lee@example.com   22  데이터분석 2026-09-17 15:52:28.826805
2   3  박민수  park@example.com   23    웹개발 2026-09-17 15:52:28.826805
3   4  최지훈  choi@example.com   24   임베디드 2026-09-17 15:52:28.826805
4   5  정수빈  jung@example.com   20   클라우드 2026-09-17 15:52:28.826805
5   6  주예찬   joo@example.com   24   인공지능 2026-09-18 10:38:35.686845
6   7  이찬혁   lee@example.com   26   임베디드 2026-09-18 10:38:35.686845
7  11  애슐리  ashely@gmail.com   30   영어영문 2026-09-22 12:10:18.680210
8  12   소니   sonny@gmail.com   30  체육교육과 2026-09-22 13:51:38.155085
9  13  홍길동    hong@gmail.com   22   정치학과 2026-09-22 16:57:38.813764

- PostgresSQL로 데이터 저장은 추후

### 실습

- 상품데이터 활용

In [120]:
data = {
    'product' : ['키보드', '마우스', '모니터', 'USB', '노트북'],
    'category' : ['주변기기', '주변기기', '디스플레이', '저장장치', '컴퓨터'],
    'price' : [30000, 15000, 250000, 12000, 1200000],
    'stock' : [10, 30, 5, 50, 3]
}

df_products = pd.DataFrame(data)

1. 전체 데이터 출력
2. product, price 컬럼 출력
3. 가격이 50000원 이상인 상품만 출력
4. 재고가 10개 이상인 상품만 출력
5. total_value 컬럼 추가, 계산식은 price * stock
6. 전체 재고 가치의 합계 출력
7. 카테고리가 주변기기인 상품만 출력

In [ ]:
# 1. 전체 데이터 출력

df_products

  product category    price  stock
0     키보드     주변기기    30000     10
1     마우스     주변기기    15000     30
2     모니터    디스플레이   250000      5
3     USB     저장장치    12000     50
4     노트북      컴퓨터  1200000      3

In [ ]:
# 2. product, price 컬럼 출력

df_products[['product', 'price']]

  product    price
0     키보드    30000
1     마우스    15000
2     모니터   250000
3     USB    12000
4     노트북  1200000

In [ ]:
# 3. 가격이 50000원 이상인 상품만 출력

df_products[df_products['price'] >= 50000]

  product category    price  stock
2     모니터    디스플레이   250000      5
4     노트북      컴퓨터  1200000      3

In [127]:
# 4. 재고가 10개 이상인 상품만 출력

df_products[df_products['stock'] >= 10]

  product category  price  stock
0     키보드     주변기기  30000     10
1     마우스     주변기기  15000     30
3     USB     저장장치  12000     50

In [131]:
# 5. total_value 컬럼 추가, 계산식은 price * stock

df_products['total_value'] = df_products['price'] * df_products['stock']

df_products

  product category    price  stock  total_value
0     키보드     주변기기    30000     10       300000
1     마우스     주변기기    15000     30       450000
2     모니터    디스플레이   250000      5      1250000
3     USB     저장장치    12000     50       600000
4     노트북      컴퓨터  1200000      3      3600000

In [132]:
# 6. 전체 재고의 합계 출력

df_products['total_value'].sum()

np.int64(6200000)

In [134]:
# 7. 카테고리가 주변기기인 상품만 출력

df_products[df_products['category'] == '주변기기']

  product category  price  stock  total_value
0     키보드     주변기기  30000     10       300000
1     마우스     주변기기  15000     30       450000

In [138]:
df.to_csv('../data/상품정보.csv', encoding='utf-8')